[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__"]
defineConstant = { DEBUG = true }

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.11.7"
pythonPlatform = "Linux"
